### ISSUE TITLE
[SPIKE] Research on 1st page to implement

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/vsf-capybara#14]
Result of that task should be a list of elements to be done to get the 1st page up and running.

**Comment by psmyrek** [comment]
After a quick investigation it looks like that the best choice to start actual development would be from Home Page. Example Home Page implementation from `Storefront UI` is already available, so to start it s needed to replace current Home Page with this one from `Storefront UI` and prepare/update data interfaces which have changed.
