### ISSUE TITLE
Selected menu option should stay opened and be selected in menu

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vsf-capybara#208]
The left menu is not keeping the current option expanded and selected (Women should stay expanded, "View all" should  be marked - bold whatever)

![Screenshot 2020-02-25 15 52 18](https://user-images.githubusercontent.com/211899/75258611-07508200-57e7-11ea-8178-8ffadc09544e.png)

**Comment by psmyrek** [comment]
Regarding keeping the current menu item expanded - I've created a bug in Storefront UI: https://github.com/DivanteLtd/storefront-ui/issues/790
The second issue to mark current menu item in bold is in progress - PR is created.
