### ISSUE TITLE
Search bar - categories bar is not properly styled

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vsf-capybara#209]
This is a pretty useful option so we can leave it but we need to add proper margins and set the right font

![Screenshot 2020-02-25 15 54 38](https://user-images.githubusercontent.com/211899/75258826-5696b280-57e7-11ea-9d77-9422e1dc50de.png)

**Comment by gibkigonzo** [comment]
This should be done based on design https://www.figma.com/file/hrwE3VsMBHgdJoS86rVr4W/Desktop-%26-Mobile-Vue-Storefront?node-id=9338%3A7843

**Comment by psmyrek** [comment]
According to latest news from Storefront UI team, they will start working on some examples regarding search results for desktop and mobile view not earlier than at the end of March.
