### ISSUE TITLE
My Account - Menu - no margins between sectrons

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vsf-capybara#219]
![Screenshot 2020-02-26 15 06 43](https://user-images.githubusercontent.com/211899/75352196-a63db280-58a9-11ea-8c0c-9482253383fc.png)

**Comment by psmyrek** [comment]
After updating Storefront UI to v0.6.x it looks much better now:

![219](https://user-images.githubusercontent.com/56868128/76517009-c69a6f00-645c-11ea-8454-0c21f2327e39.png)

So I'm closing this issue.
