### ISSUE TITLE
PDP: The default tab should be "Description"

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vsf-capybara#222]
... now the default tab is "Reviews" which is 99% emtpy
![Screenshot 2020-02-26 15 11 09](https://user-images.githubusercontent.com/211899/75352584-44ca1380-58aa-11ea-8a1c-0af2a300914b.png)

**Comment by qiqqq** [comment]
This problem not occurs. It was fixed in one previous PR. I am closing this issue.
