### ISSUE TITLE
Tabs on the product page are not reset properly

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/vsf-capybara#228]
## Current behavior
If the user switches to `Read reviews`,  then each newly viewed PDP page will display a view with reviews, instead of displaying 'Description' by default

## Expected behavior
By default, first tab (Description in our case) should be opened

## Steps to reproduce the issue
1. Go to any PDP
2. Switch to "Read reviews"
3. Change PDP

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details
- Browser: All
- OS: All
- Code Version: All

## Additional information
No additional information

**Comment by alinadivante** [comment]
@qiqqq now there is the same problem
