### ISSUE TITLE
You cannot add specific product that is available in large quantities.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-capybara#230]
## Current behavior
Despite the information that product is available in Quantity 88, when you try to add it to the cart, the message "The product you are trying to add is not available" occurs

![image](https://user-images.githubusercontent.com/36628922/75420950-7938e080-5939-11ea-9958-fea64f9bc50a.png)

## Expected behavior
Product should be added to the cart.

## Steps to reproduce the issue
1. Open this product https://capybara.storefrontcloud.io/men/bottoms-men/pants-men/pants-18/aether-gym-pant-872.html?childSku=MP11-32-Blue
2. Add to cart"

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by gibkigonzo** [comment]
This is not related with capybara, more info here https://github.com/DivanteLtd/vue-storefront/issues/4152
