### ISSUE TITLE
Add megamenu

### ISSUE THREAD

**Issue by qiqqq** [DivanteLtd/vsf-capybara#252]
## What is the motivation for adding/enhancing this feature?
The current navigation is poor. SF UI prepared design for mega menu, so we should add this feature.

## What are the acceptance criteria?
- [ ] Megamenu shows on main menu item mouseover
- [ ] Megamenu contains categories and subcategories
- [ ] User can go through megamenu directly to specific subcategory

## Can you complete this feature request by yourself?
- [x] YES
- [ ] NO

## Additional information
https://storybook.storefrontui.io/?path=/story/organisms-megamenu--with-sfheader

**Comment by gibkigonzo** [comment]
duplicate https://github.com/DivanteLtd/vsf-capybara/issues/23
