### ISSUE TITLE
Registering customer in website is triggered twice. 

### ISSUE THREAD

**Issue by booraa0a** [DivanteLtd/vsf-capybara#298]
## Current behavior

When I tried to register account using demo https://capybara.storefrontcloud.io/, I got two messages one login success and other error message saying that there is already customer with same email.   I traced the issue in the inspector and found out the create API is triggered twice. 

## Expected behavior

Only one message should be shown  and create API button should be triggered once per click. 

## Steps to reproduce the issue

1- Open the browser inspector (network)
2-Register an account in the demo https://capybara.storefrontcloud.io/ 
3- Will notice two messages success and error on the same time. 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Environment details

- Browser: Firefox ,  74.0.1 
- OS:  MacOs, Mojave
- Code Version:  v1.11.1

**Comment by psmyrek** [comment]
Hi @booraa0a, thanks for reporting this issue. Similar error (doubled API calls) was also during logging in and resetting a password. All of them will be fixed by my PR  😃
