### ISSUE TITLE
No possible to remove the discount code from the cart.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-capybara#323]
## Current behavior
It is not possible to remove the discount code from the cart.
And on the checkout the button for removing the discount code requires text to be centered.
![image](https://user-images.githubusercontent.com/36628922/79950918-14e95780-8478-11ea-8841-be0d64aa5c55.png)

## Expected behavior
User is able to delete discount code on the cart.

## Steps to reproduce the issue
1. Add product to the cart
2. Open cart and apply discount code, e.g. mmtest
3. Try to delete applied code
4. Go to checkout and look at `DELETE DISCOUNT CODE` button

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by psmyrek** [comment]
There was a problem with Vue Storefront. After fetching latest changes from `develop` branch from there it is now possible to add and remove discount codes.
