### ISSUE TITLE
Two minuses next to currency after applying the discount coupon

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-capybara#324]
## Current behavior
Two minuses next to currency after applying the discount coupon (cart & checkout).
![image](https://user-images.githubusercontent.com/36628922/79950179-f20a7380-8476-11ea-80e3-36eb85805f78.png)

## Expected behavior
There should by only one minus, eg. -$34.50

## Steps to reproduce the issue
1. Add product to the cart
2. Apply coupon code (e.g. mmtest)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by psmyrek** [comment]
Fixed in Vue Storefront in https://github.com/DivanteLtd/vue-storefront/issues/4353
Now it works as expected:

![after](https://user-images.githubusercontent.com/56868128/81657274-091a0100-9438-11ea-85bb-25e329e490f6.png)
