### ISSUE TITLE
5 problems with capybara (Production mode, Mega menu, Wishlist, Filtration, Refresh product page)

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vsf-capybara#326]
Hello dear developers. Thanks for your great digital products. I really like that you make the world a better place, like your ideas. But please take me out of the dense forest, show me the way:
**I have just 4 questions. I'll start with the most important.**

- **1.)** The most important thing that concerns me today is how to switch to the production mode in the Capybara theme, for example, in the default theme, I just start yarn start in the VSF folder, at that time the dispatcher (PM2) starts.
And in Capybara I know only one lerna command bootstrap && yarn dev. The question is if I now edit the Capybara theme for my needs, how visitors to my site in vue storefront will interact with the Capybara theme if the Capybara only works in development mode. What is the point of this topic then?
Below I show two pictures first after the yarn start command, where default theme starts. And the second picture is capybara. So, in the case of the theme "Capybara" the application does not start.

![default](https://user-images.githubusercontent.com/20755897/79949492-458aba80-8493-11ea-932a-0e71b7f831a0.png)

![capybara](https://user-images.githubusercontent.com/20755897/79949510-4de2f580-8493-11ea-8e3a-26d9c4f9d7e8.png)

- **2.)** Where did the child menu items disappear in the Capybara theme.That's what I meant

![default_theme_desktop2](https://user-images.githubusercontent.com/20755897/79949643-7cf96700-8493-11ea-9948-cd0e2978dde3.png)

![default_theme_desktop](https://user-images.githubusercontent.com/20755897/79949672-85ea3880-8493-11ea-9dec-2d834173214a.png)

![capybara_menu_desktop](https://user-images.githubusercontent.com/20755897/79949680-8a165600-8493-11ea-8087-a43d8b63b924.png)

![capybara_menu](https://user-images.githubusercontent.com/20755897/79949690-8da9dd00-8493-11ea-9b1c-0e6b8bba2b33.png)

**At the same time, I noticed that you have this correct extended menu for magento 2. It is only present on your demo site, but it is not in the repository.**

![good_menu_capybara](https://user-images.githubusercontent.com/20755897/79952089-7b31a280-8497-11ea-9193-b18ecce40e13.png)

- **3.)** I think it would be advisable to place the wishlist button on the product page in Capybara, since this is an e-commerce format, especially since it is in your repository, but it’s turned off, I tried to turn it on but it didn’t work
**Here's what the work button looks like in the default theme.**

![default_theme_desktop_wishlist](https://user-images.githubusercontent.com/20755897/79950167-43752b80-8494-11ea-808e-579016630ecc.png)

- **4.)** I also noticed that the product is not filtered by price, the filter displays "nothing was found". This problem is observed in two topics, the default and Capybara. I am sure that you know about this problem, but it would be nice if you suggested how to solve it
There are several issues that still prevent me from releasing my site on Vue Storefront. I like some things in the default theme, such as: “wish list button”, “add to comparison button”, “full menu from magento 2”.
Filtered by price, only on your demo sites, but not from the repositories https://github.com/DivanteLtd/vsf-capybara and https://github.com/DivanteLtd/vsf-default

![good_filter_by_price](https://user-images.githubusercontent.com/20755897/79952919-c304f980-8498-11ea-8ff3-8fb89bb6673e.png)

- **5.)** When I refresh the page in the product card of my site (Ctrl + R), I get redirected to the error page (I get an error on the page). But when I do Ctrl + R on your product site in the product card, it works correctly, that is, I continue to remain on the page. For example, on this page everything works, but it doesn’t work on my site
https://capybara.storefrontcloud.io/women/tops-women/tees-women/tees-25/gabrielle-micro-sleeve-top-1417.html?childSku=WS02-XS-Blue

**How to beat this?**

But I do not see these things in the Capybara theme, even in version v1.11.2. I understand that the atomic approach in Capybara is a great solution. but lack of buttons: "wish list", "add to comparison" and limited menu. How to solve these problems in Capybara?

**Thanks again for what you are doing. We will be very happy if you help us / tell us**

**I would really appreciate if there were tips at the copy / paste level since I can't write code**

**Comment by gibkigonzo** [comment]
1. `lerna bootstrap && yarn dev` triggers `yarn dev` in vsf directory. https://github.com/DivanteLtd/vsf-capybara/blob/develop/package.json#L9 Thats because capybara can't work without vsf. If you want to have capybara in production mode then just use same building process as for vsf. `yarn build && yarn start` from vsf directory

**Comment by ArieRym** [comment]
1.) What you mean. Can you specify the commands sequentially, since if you mean first, from vsf directory I run
`yarn build && yarn start`
then
`lerna bootstrap && yarn dev`
A button appears in the address bar it really works and I get the "Install app?". Then, after I install it on the desktop, then I edited the capybara theme and no longer need the developer mode. I exit it developer mode, after this application stops working.

**Comment by gibkigonzo** [comment]
From vsf directory:
- `yarn build` => creates `dist` where are your app files
- `yarn start` => starts pm2 process which serves files from `dist` folder
- `yarn dev` => starts app in dev mode (webpack)

From capybara theme directory there is only:
- `lerna bootstrap && yarn dev` => which starts `yarn dev` from vsf directory :point_up: 

2,3,4,5 => it's not possible to help you if there is no error message or at least some information what did you changed in vsf or in capybara theme :) 
2 => did you applied this https://github.com/DivanteLtd/vsf-capybara/blob/develop/local.json config changes into your local.json file?

**Comment by ArieRym** [comment]
Thank you for the ability to help, today I will check everything.

**Comment by GaneshMBabu21** [comment]
I have the same issue, Can any one help ??

**Comment by GaneshMBabu21** [comment]
> Thank you for the ability to help, today I will check everything.

Did you over come the issues ?
