### ISSUE TITLE
Product rating - display the correct number of product stars on the category page

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-capybara#327]
## What is the motivation for adding/enhancing this feature?
It would be helpful if the user could see how the product is rated already on the category page or in the search results.
Now all products have full stars displayed.
PLP:
![image](https://user-images.githubusercontent.com/36628922/79966208-5f290380-848d-11ea-8941-2907d734210a.png)
PDP:
![image](https://user-images.githubusercontent.com/36628922/79966173-52a4ab00-848d-11ea-9d82-aae5e12e04ed.png)

## What are the acceptance criteria?
Display the same number of stars on the category page as on PDP.

![image](https://user-images.githubusercontent.com/36628922/79966846-51c04900-848e-11ea-8b31-8bfaf5232755.png)

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by psmyrek** [comment]
Duplicated with https://github.com/DivanteLtd/vsf-capybara/issues/27 so I'm closing this one.

**Comment by ArieRym** [comment]
@gibkigonzo  Problem still exists!
