### ISSUE TITLE
Wrong images in Product gallery.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vsf-capybara#334]
## Current behavior
Duplicates and incorrect images in the product gallery.

![image](https://user-images.githubusercontent.com/36628922/79980456-6824cf80-84a3-11ea-9bb0-60a05efb857c.png)

## Expected behavior
Product gallery should contain correct images.

## Steps to reproduce the issue
1. Go to PDP, e.g https://capybara.storefrontcloud.io/women/tops-women/jackets-women/jackets-23/olivia-14-zip-light-jacket-1401.html?childSku=WJ12-XS-Black
2. Check gallery

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by psmyrek** [comment]
Exactly the same images for this product are shown on demo site: https://test.storefrontcloud.io/women/tops-women/jackets-women/jackets-23/olivia-14-zip-light-jacket-1401.html?childSku=WJ12

![Screenshot_2020-04-23 Olivia 1 4 Zip Light Jacket - Vue Storefront](https://user-images.githubusercontent.com/56868128/80074502-8b09bf00-8549-11ea-897b-f18d50a29f28.png)

This can't be an issue in Capybara theme, but rather Magento configuration - so I'm closing this issue.

**Comment by Iamwade** [comment]
https://capybara.storefrontcloud.io/women/tops-women/jackets-women/jackets-23/inez-full-zip-jacket-1305.html?childSku=WJ07-XS-Orange
