### ISSUE TITLE
I can not install capybara

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vsf-capybara#359]
Following your installation scenario, for some reason, capybara stopped running. Everything used to run
I get an error: "lerna: command not found"

OS Ubuntu 18.04

**Comment by psmyrek** [comment]
Do you have `lerna` installed globally?

**Comment by ArieRym** [comment]
I didn’t install it specifically, I installed nginx, docker, redis, elastic search 7.3 on a clean ubuntu, then vue-storefront, vue-storefront-api, mage2, then capybara, I did it so many times and it worked

**Comment by psmyrek** [comment]
Could you describe how did you install capybara theme? Did you follow instructions from here https://github.com/DivanteLtd/vsf-capybara#--installation?

**Comment by ArieRym** [comment]
Absolutely right

**Comment by psmyrek** [comment]
The first point in this instruction is to install `lerna` globally. This requirement is here since the beginning of capybara theme.

**Comment by ArieRym** [comment]
I write about this and that I did everything according to the instructions, but there is no result

**Comment by psmyrek** [comment]
There could be multiple reasons why `lerna` command is not found in your OS.
Could you please re-install `lerna`?

**Comment by ArieRym** [comment]
I have already reinstalled 3 times

**Comment by psmyrek** [comment]
OK, so then please try re-installing it with `sudo` and if it will not help then please try installing `lerna` globally via `npm` command.

**Comment by ArieRym** [comment]
Can I clarify what to reinstall through sudo? NPM issues errors

**Comment by ArieRym** [comment]
psmyrek Tell me what you think about it.

**Comment by ArieRym** [comment]
The question remains open how to solve the problem. I think now such a problem will not only arise for me. I reinstall the system.
I installed Ubuntu 18.04, docker, nginx, nodejs 12, yarn, redis, Elasticsearch 7.x, mariadb, magento 2.3, vue storefront 1.11.3, vue-storefront-api 1.11.1, mage2, everything works
But when I install according to the instructions VSF Capybara 1.0-rc.1, vue storefront writes error, Tell me why lerna does not start, I count on a more specific reason and how to fix it.

![9c378c6aa15](https://user-images.githubusercontent.com/20755897/81493439-01365180-92be-11ea-8259-2bde228c4540.png)

**Comment by ArieRym** [comment]
I also tried to install install through cli, but I'm not sure that I correctly understood how?

![2020_05_10_12_52_55](https://user-images.githubusercontent.com/20755897/81493518-8457a780-92be-11ea-8631-37eff678bd84.png)

**Comment by psmyrek** [comment]
We are working on CLI update to make the whole process of installing themes easier. For now some manual adjustments are needed. As a temporary workaround please check the following:
- change capybara branch to `develop`
- call `yarn && yarn dev`

Current configuration in `local.json` file in capybara repo utilizes some recent performance optimizations which were implemented in vsf and vsf-api so they require latest versions of vsf and vsf-api - both are only on `develop` branches because they are not yet released. But as I see you will use vsf v1.11.3 and vsf-api v1.11.1 so just make sure that `server.api="api"` in your configuration.

**Comment by ArieRym** [comment]
In which file change capybara branch to develop?
Where to change this value "server.api="api""

**Comment by psmyrek** [comment]
If you followed the instruction then you should have capybara installed as a git submodule, so please go to the capybara source code from root vsf folder: `cd src/themes/capybara` and then call `git checkout develop`. After that please check your `local.json` configuration in root vsf folder and make sure that there is `server.api="api"`.

**Comment by ArieRym** [comment]
Ok. But I have some problems after
[2/5] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...

**Comment by psmyrek** [comment]
There seems to be some problems with your network connection so in this case please call `yarn && yarn dev` one more time.

**Comment by ArieRym** [comment]
Thank you very much for your work, I launched. But three more questions remain:
1. When release the production version
2. If there is git checkout develop, then how to switch to production
3. The menu in the header does not work even the parent level

**Comment by psmyrek** [comment]
I'm glad I could help. The whole process will be much simpler soon. We are currently in development phase and the goal is to have it with v1.12.
The "production" version will be on master branch but it has currently some problems that will be fixed by https://github.com/DivanteLtd/vsf-capybara/pull/362.
And the problem with header is already addressed in this issue: https://github.com/DivanteLtd/vsf-capybara/issues/360

**Comment by ArieRym** [comment]
Then not a lot of accuracy
2. That is, as soon as the problem is solved (I wonder if there is an approximate deadline solution to this problem?). Do I need to update my code? If so, then I honestly did not understand how to update my code so that there were corrections on my site.
3. Regarding the third point of questions. Is it possible to install @storefront-ui/vue@0.7.10 or do I need to install @storefront-ui/vue@0.7.9 for the menu to work with subcategories. How to install? Do I understand correctly, you just need to replace the main @ storefront-ui folder in node_modules from the downloaded and unpacked zip archive from the page https://github.com/DivanteLtd/storefront-ui/releases
Then yarn build && yarn && yarn dev? Or is there an easier way, not so awkward. What commands to write in the console?

**Comment by psmyrek** [comment]
When the CLI and v1.12 of vue-storefront will be updated and released, then the whole process will be different (simpler) than you did. You already have fetched and installed the capybara theme so you can work with it. If you want to merge some bug fixes then you must do it by yourself using `git` commands.
The problem with menu items in header, as mentioned above, is already addressed in https://github.com/DivanteLtd/vsf-capybara/issues/360. After it is merged you can pull those changes.
