### ISSUE TITLE
Support Storefront UI v0.7.9+

### ISSUE THREAD

**Issue by psmyrek** [DivanteLtd/vsf-capybara#360]
## Current behavior

Currenty there are some breaking changes in Storefront UI in v0.7.9 which broke our header with mega menu and search panel.

## Expected behavior

Header with mega menu and search panel works correctly.

## Steps to reproduce the issue

1. Upgrade Storefront UI lib to v0.7.9
2. Check mega menu and search panel - it does not look nice.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: any
- OS: any
- Code Version: latest

**Comment by ArieRym** [comment]
It turns out that Storefront UI v0.7.10 was automatically installed with yarn. I tried in src / themes / capybara / package.json in the line "@ storefront-ui / vue": "^ 0.7.8", replace it with "^ 0.7.9", Then yarn && yarn dev. But this did not fix the menu problem. What have I done wrong?

**Comment by psmyrek** [comment]
The problem with Storefront UI library that always installs latest "shared" package (regardless of fixed "vue" package version in `package.json`) will be tracked in https://github.com/DivanteLtd/storefront-ui/issues/1176.
