### ISSUE TITLE
Support theme configuration via CLI

### ISSUE THREAD

**Issue by psmyrek** [DivanteLtd/vsf-capybara#369]
## What is the motivation for adding/enhancing this feature?

It may happen that theme configuration in `local.json` depends on installed VSF version (i.e. some options may be invalid for older VSF version), so CLI should be able to configure downloaded theme for VSF version, which is installed.

Related issue: https://github.com/DivanteLtd/vue-storefront/issues/4395

## What are the acceptance criteria?

- [ ] There is possibility to output `local.json` depending on VSF version

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by benoitemile** [comment]
Could you please reflect those changes in readme.md ? because for now, when following Readme, there's no way to do the step 4, `cp local.json`, it's misleading.
