### ISSUE TITLE
Product images doesn't change in PDP

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/vsf-capybara#380]
## Current behavior

When user changes product color, then product image should be change in product gallery
https://capybara.storefrontcloud.io/olivia-1-4-zip-light-jacket.html?childSku=WJ12-XS-Black

![Zrzut ekranu z 2020-06-08 08-08-31](https://user-images.githubusercontent.com/42383376/83997704-44d4b780-a95f-11ea-8aeb-fa02ee5db0a2.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by ArieRym** [comment]
@gibkigonzo When I switch to the default.json "mergeConfigurableChildren": false,, they switch, but not quite correctly, the first image only changes when I select it in the thumbnails, then it switches when the color is selected, but I think that it does not work correctly.

**Comment by gibkigonzo** [comment]
done
