### ISSUE TITLE
Products in bestsellers section should be wider

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/vsf-capybara#382]
## Current behavior

Products on homepage in section bestsellers should be wider. 
![Zrzut ekranu z 2020-06-08 08-19-06](https://user-images.githubusercontent.com/42383376/83998678-6898fd00-a961-11ea-92d1-3256bab1e04d.png)

## Expected behavior

Should look like in related products on PDP
![Zrzut ekranu z 2020-06-08 08-23-50](https://user-images.githubusercontent.com/42383376/83998685-6afb5700-a961-11ea-80d7-d0ec8ddb2121.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by AishwaryShrivastav** [comment]
`.section {
  padding-left: var(--spacer-xl);
  padding-right: var(--spacer-xl);
  @include for-desktop {
    padding-left: 0;
    padding-right: 0;
  }
}`

This CSS was adding unnecessary padding on the 'bestseller' carousal and 'share your look' section 
Removed the **above two properties** which will give space to these section, in my above PR.

Also this will align these two section with the width of all other sections of the home page.
Currently, theses section are smaller in width than other sections in the home page.

Thanks!!
