### ISSUE TITLE
No child menu displayed, The pictures does not switch, All products are not available for purchase, Bestsellers without products,A short description is duplicated, No full description, Missing attributes tab, Missing Pages From (Magento CMS), Stars are not displayed correctly

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vsf-capybara#384]
The finishing touches are left :)

1) No child menu displayed

![Home_Page_Vue_Storefront](https://user-images.githubusercontent.com/20755897/83994095-09dc7f00-a973-11ea-90f5-bc0ca4a9ae7c.jpg)

2) On the product page, the image does not change when switching colors

![Nadia_Elements_Shell_Vue_Storefront](https://user-images.githubusercontent.com/20755897/83994168-3395a600-a973-11ea-9651-d8ea2cb55d49.jpg)

3) All products are not available for purchase

![Nadia_Elements_Shell_Vue_Storefront2](https://user-images.githubusercontent.com/20755897/83994179-414b2b80-a973-11ea-944d-275486a8543d.jpg)

4) There are no products on the main page in the Bestsellers block

![Home_Page_Vue_Storefront2](https://user-images.githubusercontent.com/20755897/83994202-4e681a80-a973-11ea-888d-3e135d1d2862.jpg)

5.) A short description is duplicated
6.) No full description
7.) Missing attributes tab

![Vue_Storefront](https://user-images.githubusercontent.com/20755897/84017005-b9c5e280-a99b-11ea-8aa1-ffec47f0fa94.jpg)

8.) Missing Pages From (Magento CMS)

![404_Not_Found_Vue_Storefront](https://user-images.githubusercontent.com/20755897/84019168-8d5f9580-a99e-11ea-8fad-0b500af3d400.jpg)

9.) Stars are not displayed correctly

![Women_Vue_Storefront](https://user-images.githubusercontent.com/20755897/84019210-9a7c8480-a99e-11ea-9130-11ef8fb30421.jpg)

Vsf version 1.12
Magento ver. 2.3.5-p1

It would be nice to hear a second opinion from @psmyrek or @qiqqq or @gibkigonzo

**Comment by akrajna** [comment]
ad.1 it is working now 
<img width="776" alt="ChildMenuKapibara" src="https://user-images.githubusercontent.com/57936972/84047881-e255d880-a9ab-11ea-955f-7cbe8b37ae8f.png">
ad. 2 an issue has been created: #385 
ad. 3 not all product variants are available for purchase; if the selected product variant is not available, the user receives the information "The selected variant is not available" and cannot add this product to the basket - this is the desired action.
<img width="758" alt="OutOfStock" src="https://user-images.githubusercontent.com/57936972/84051750-dd932380-a9af-11ea-9947-0ab55e784b0a.png">
ad. 4 it is working now 
<img width="694" alt="bestseller" src="https://user-images.githubusercontent.com/57936972/84051983-3793e900-a9b0-11ea-87f4-35a5f4dc16d5.png">
ad. 5 and 6 - it is working now
<img width="469" alt="description" src="https://user-images.githubusercontent.com/57936972/84052394-cd2f7880-a9b0-11ea-806c-220d9c216bf4.png">
ad. 7 an issue has been created #386
ad. 8 it is working now 
<img width="666" alt="Magento CMS" src="https://user-images.githubusercontent.com/57936972/84053379-1af8b080-a9b2-11ea-9e19-f006e7df1052.png">
ad. 9 an issue has been created #387

**Comment by ArieRym** [comment]
@gibkigonzo What do you think about this?

**Comment by ArieRym** [comment]
3.) None of the goods can be bought, although magento is available for purchase and has stock

**Comment by ArieRym** [comment]
7.) there are two problems, not only with no tabs, but from a duplicate brief description, where there should be a full description

**Comment by ArieRym** [comment]
@akrajna  I see the latest changes to the capybara theme 7 days ago. and I set the topic 2 days ago. Where to see new changes

**Comment by akrajna** [comment]
@gibkigonzo could you please answer ArieRym question?

**Comment by akrajna** [comment]
@ArieRym Does what you wrote in 3.) correspond to the description of this #389 issue?

**Comment by ArieRym** [comment]
@akrajna not enough, for any manipulation I have inaccessible active green button "ADD TO CART"
Vsf version 1.12
Magento ver. 2.3.5-p1

**Comment by gibkigonzo** [comment]
> @akrajna I see the latest changes to the capybara theme 7 days ago. and I set the topic 2 days ago. Where to see new changes. Or how to update a theme? Interested in a specific command

@ArieRym there were no new changes at that time.

- 3. lets keep conversation in this issue https://github.com/DivanteLtd/vsf-capybara/issues/377 it should work in same why as it is on https://demo.storefrontcloud.io/
- 5. here is issue https://github.com/DivanteLtd/vsf-capybara/issues/393
- 7. here is issue https://github.com/DivanteLtd/vsf-capybara/issues/386
- and rest is as @akrajna wrote

I will close this issue, please @ArieRym create one issue for one bug/feature. It will be easier to manage :)

**Comment by ArieRym** [comment]
ok
