### ISSUE TITLE
[Bug] Switch color does not switch picture on product page

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-capybara#385]
## Current behavior
On the product page, the image does not change when switching colors.

## Expected behavior
The picture should change according to the chosen color. So if user clicks on red square in color section the picture with red item should appear. 

## Steps to reproduce the issue
1. go on any product page
2. click on any color square
3. check if the picture with item in chosen color appears

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details
https://capybara.storefrontcloud.io/

## Additional information
![ColorChangePP](https://user-images.githubusercontent.com/57936972/84049844-39a87880-a9ad-11ea-89d4-077f7d1d26fe.gif)

**Comment by one1note** [comment]
Setting gallery.mergeConfigurableChildren in your local config to false fixed the above for me.

**Comment by gibkigonzo** [comment]
should be fixed in 1.0.2
