### ISSUE TITLE
[Bug] Missing attributes tab on Product Page

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-capybara#386]
## Current behavior
There is no attributes tab on Product Page

## Expected behavior
There should be 'Additional information' tab on Product Page as below:
<img width="892" alt="additional information" src="https://user-images.githubusercontent.com/57936972/84054513-cd7d4300-a9b3-11ea-8139-c05a8e4a76ac.png">

## Steps to reproduce the issue
1. go to any product page
2. scroll down to the place where 'Description' and 'Read reviews' tabs are
3. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details
https://capybara.storefrontcloud.io/

## Additional information
<img width="868" alt="atribiutts" src="https://user-images.githubusercontent.com/57936972/84053075-b63d5600-a9b1-11ea-904b-bf7b6602e72e.png">

**Comment by gibkigonzo** [comment]
there are attributes under description https://capybara.storefrontcloud.io/advanced-pilates-yoga-strength.html
![Screenshot from 2020-06-09 18-23-08](https://user-images.githubusercontent.com/42383376/84173981-4a74ef00-aa7e-11ea-88d5-71a9f7ccef7f.png)
those are attribute: 
```
Activity: Yoga, Athletic, Gym
Format: Download
```
but it is good idea to create new tab and move there attributes :+1:

**Comment by ArieRym** [comment]
My attributes are not showing at all, what should I do? What did you do to see the attributes?
Vsf версия 1.12
Elasticsearch 7
Magento ver. 2.3.5-p1

**Comment by ArieRym** [comment]
@gibkigonzo  Attributes added in ES7, but they are not displayed in capybara

![Screenshot_from_2020_06_10_12_12_50](https://user-images.githubusercontent.com/20755897/84235756-03393d80-ab14-11ea-8879-6b951e5a9eac.jpg)

**Comment by AishwaryShrivastav** [comment]
Hey @gibkigonzo, as per your comment, I have added a new tab and moved the product attributes there, I have named the tab "Additional Information" as mentioned in the image on top. 
Please review.
Thanks!!

**Comment by AishwaryShrivastav** [comment]
Here is quick video on this issue and its PR 
https://www.youtube.com/watch?v=rPFNIiWP2mo&feature=youtu.be
