### ISSUE TITLE
[Bug] Add to cart is not working for configurable products

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-capybara#389]
## Current behavior
It is impossible to add items with configurable options (size, color) to the cart. The message 'You need to choose option for your item' appears even if the options are already chosen.

## Expected behavior
After selecting options and  clicking on 'Add to cart' button, if product is available, it should be added to the cart.

## Steps to reproduce the issue
1. go to any product page
2. select size
3. select color
4. click 'add to cart' button
5. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

https://capybara.storefrontcloud.io/ 
- Browser: Chrome, Firefox, Safari
- Mobile (iOS, Android) and desktop

## Additional information
![AddToCart](https://user-images.githubusercontent.com/57936972/84134752-572b2000-aa49-11ea-9cd5-7fb4786ba573.gif)

**Comment by gibkigonzo** [comment]
@akrajna please recheck this, it should be fixed now. Problem was with our server configuration

**Comment by akrajna** [comment]
Rechecked -works fine :-)

**Comment by gibkigonzo** [comment]
thanks :)
