### ISSUE TITLE
[Bug] Subscribe to newsletter does not work

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-capybara#390]
## Current behavior
Subscribe to newsletter does not work, after clicking on 'subscribe' button the message 'An error occurred while accessing Mailchimp' appears

## Expected behavior
After providing correct email and clicking on 'subscribe' button user gets the message like this: 'Congratulations, you have been subscribed to the newsletter!' and the user is subscribed to newsletter.

## Steps to reproduce the issue
1. go to home page
2. scroll down to the 'Subscribe to Newsletter' section
3. click 'subscribe' button
4. enter your email
5. click 'subscribe' button
6. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
![Newsletter](https://user-images.githubusercontent.com/57936972/84139580-6bbee680-aa50-11ea-89ef-3cbefada4b53.gif)

**Comment by pkarw** [comment]
This is a Mailchimp misconfig not actuall Capybara's bug - closing for now
