### ISSUE TITLE
All products are not available for purchase

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vsf-capybara#394]
All products are not available for purchase.
Reinstalled magento 2.3.3 with data, reloaded indexes for Elasticsearch 7, installed fresh VSF, API VSF, Capybara, but nothing changed, no products are available for purchase. What should be done?

![Nadia_Elements_Shell_Vue_Storefront2](https://user-images.githubusercontent.com/20755897/83994179-414b2b80-a973-11ea-944d-275486a8543d.jpg)

## Can you handle fixing this bug by yourself?
- [ 1] NO

## Environment details

- Browser: Google Chrome 83.0.4103.97
- OS: Ubuntu 18.04 LTS
- Code Version: Capybara 1.0.1

**Comment by gibkigonzo** [comment]
duplicate https://github.com/DivanteLtd/vsf-capybara/issues/377
