### ISSUE TITLE
There are no products on the main page in the Bestsellers block

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vsf-capybara#395]
There are no products on the main page in the Bestsellers block
Reinstalled magento 2.3.3 with data, reloaded indexes for Elasticsearch 7, installed fresh VSF, API VSF, Capybara, but nothing changed, there are no products on the main page in the Bestsellers block. What should be done?

![Home_Page_Vue_Storefront2](https://user-images.githubusercontent.com/20755897/83994202-4e681a80-a973-11ea-888d-3e135d1d2862.jpg)

## Can you handle fixing this bug by yourself?
- [ ] YES
- [ 1] NO

## Environment details

- Browser: Google Chrome 83.0.4103.97
- OS: Ubuntu 18.04 LTS
- Code Version: Capybara 1.0.1

**Comment by gibkigonzo** [comment]
check what data you get in response

**Comment by ArieRym** [comment]
@gibkigonzo  Checked here is the date in ES7

![Screenshot_from_2020_06_10_12_03_17](https://user-images.githubusercontent.com/20755897/84234993-c587e500-ab12-11ea-8671-53222f497f17.jpg)
