### ISSUE TITLE
Missing Pages From (Magento CMS)

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vsf-capybara#397]
Reinstalled magento 2.3.3 with data, reloaded indexes for Elasticsearch 7, installed fresh VSF, API VSF, Capybara, but missing Pages From (Magento CMS). What should be done?

![Nadia_Elements_Shell_Vue_Storefront2](https://user-images.githubusercontent.com/20755897/83994179-414b2b80-a973-11ea-944d-275486a8543d.jpg)

## Can you handle fixing this bug by yourself?
- [ 1] NO

## Environment details

- Browser: Google Chrome 83.0.4103.97
- OS: Ubuntu 18.04 LTS
- Code Version: Capybara 1.0.1

**Comment by gibkigonzo** [comment]
this image is not related.
install chrome extension `elasticsearch head` and check if you have cms pages

**Comment by ArieRym** [comment]
Hi @gibkigonzo  Yes, I have pages there, I use it from the very beginning

**Comment by ArieRym** [comment]
@gibkigonzo Do I need to install the module https://github.com/SnowdogApps/magento2-cms-api to display CMS pages if ES7 already indexes works for me. Or what kind of magic do you need to apply to make them work?

**Comment by gibkigonzo** [comment]
https://demo.storefrontcloud.io/api/catalog/vue_storefront_catalog/cms_page/_search?from=0&request=%7B%22_availableFilters%22%3A%5B%5D%2C%22_appliedFilters%22%3A%5B%7B%22attribute%22%3A%22identifier%22%2C%22value%22%3A%7B%22like%22%3A%22customer-service%22%7D%2C%22scope%22%3A%22default%22%7D%5D%2C%22_appliedSort%22%3A%5B%5D%2C%22_searchText%22%3A%22%22%7D&request_format=search-query&response_format=compact&size=50&sort= Here you have request that is send to ES on demo. replace `https://demo.storefrontcloud.io` with your api url and check what you get

**Comment by gibkigonzo** [comment]
please also reinstall deps , because there was bug in `storefront-query-builder` https://github.com/DivanteLtd/storefront-query-builder/pull/10

**Comment by ArieRym** [comment]
Sorry for the not-so-smart question of what is deps and how to do it?

**Comment by gibkigonzo** [comment]
np, type `yarn install` and you should get updated dependencies (deps)

**Comment by ArieRym** [comment]
Thank god bless you!
