### ISSUE TITLE
[Bug] Adjust 404 error page on mobile

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-capybara#398]
## Current behavior
On mobile devices the 404 error page is not displayed correctly. The user sees only leaves on the screen. In order to see notification and 'return to home page' button, user needs to scroll down.

## Expected behavior
The whole 404 error page should bee seen, user should see notification and 'return to home page' button without scrolling down as below:
<img width="148" alt="404Design" src="https://user-images.githubusercontent.com/57936972/84239012-29eb7a00-aafc-11ea-85d3-288799dd4ad7.png">

## Steps to reproduce the issue

1. open this url on mobile: https://capybara.storefrontcloud.io/test
3. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

All mobile devices

## Additional information

![404PageAdjust](https://user-images.githubusercontent.com/57936972/84239211-759e2380-aafc-11ea-8356-f11bd7c7f381.gif)

**Comment by AishwaryShrivastav** [comment]
This issue also exists for desktop, user need to scroll down to find , return home and back buttons.
