### ISSUE TITLE
[Bug] Mobile navigation is not working

### ISSUE THREAD

**Issue by akrajna** [DivanteLtd/vsf-capybara#399]
## Current behavior
On mobile devices the bottom bar navigation is not working correctly - it is illegible and cannot be used.

## Expected behavior
The navigation on mobile devices should be legible and easy to use as below:
<img width="542" alt="MenuMobileDesign" src="https://user-images.githubusercontent.com/57936972/84245295-201a4480-ab05-11ea-87ee-f7ee3229081e.png">

## Steps to reproduce the issue

1. go to home page on mobile device
2. press the 'menu' button from bottom bar navigation
3. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

all mobile devices

## Additional information

![MobileButtomMenu](https://user-images.githubusercontent.com/57936972/84245431-5061e300-ab05-11ea-8505-faf766da0829.gif)

**Comment by vikashAppBrewery** [comment]
is there any work around or should i wait to be fixed

**Comment by AishwaryShrivastav** [comment]
This Bug fixed in https://github.com/DivanteLtd/vsf-capybara/pull/407, but updating the SFUI to V0.7.11 
I have verified it and its working perfectly.
