### ISSUE TITLE
Update Vue Storefront configuration by copying local.json file from vsf-capybara to root config directory.

### ISSUE THREAD

**Issue by ThisIsRuddy** [DivanteLtd/vsf-capybara#403]
## Current README.md states
4. Update Vue Storefront configuration by copying local.json file from vsf-capybara to root config directory.

## Expected local.json to exist
local.config.js exists but no idea where to provide it?

**Comment by gibkigonzo** [comment]
will be fixed by this pr https://github.com/DivanteLtd/vsf-capybara/pull/409 and here is issue https://github.com/DivanteLtd/vsf-capybara/issues/408
