### ISSUE TITLE
Configurable products wrong sku/stock fetch on first click

### ISSUE THREAD

**Issue by dio5** [DivanteLtd/vsf-capybara#404]
## Current behavior

On a configurable product the sku used for fetching the stock when clicking an option is incorrect on the first click. Only after the second click it uses the right one.

This happens with 2 options, but also with just one. 

On screenshot S is in stock but shows out of stock on first click.

## Expected behavior

On screenshot S is in stock so it should show in stock with the add to cart enabled.
It should enable/disable add to cart based on correct sku.

## Steps to reproduce the issue

This also happens on the demo but there it's not obvious since it's all in stock. Eg https://capybara.storefrontcloud.io/layla-tee.html?childSku=WS04-XS-Blue (~~oh yeah going to a product directly 404's as well :)~~ works now)

See screenshots

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x ] NO

## Environment details

- Browser: Chrome Version 80.0.3987.116 
- OS: Ubuntu 18.04.4 LTS
- Code Version: VSF 1.12, Capybara 1.0.1

## Additional information
It works correct on the VSF Default theme. (But there it's using different components.)

![wrong_sku](https://user-images.githubusercontent.com/628642/84895522-ba006500-b0a2-11ea-9d89-1a1542edef6b.png)
![right_sku](https://user-images.githubusercontent.com/628642/84895532-bbca2880-b0a2-11ea-9594-9bedfe4bbb8c.png)

**Comment by dio5** [comment]
![stock](https://user-images.githubusercontent.com/628642/84896127-ad304100-b0a3-11ea-99a2-28d6280d2862.png)

**Comment by gibkigonzo** [comment]
thanks for reporting this issue, it should be fixed in 1.0.2
