### ISSUE TITLE
Attribute values are displayed incorrectly in the filter

### ISSUE THREAD

**Issue by ArieRym** [DivanteLtd/vsf-capybara#430]
Installed a versions: Vue storefront api v1.12.1, Vue storefront 1.12.1, Capybara 1.0.2, Magento 2.3.5.
Attribute values are displayed incorrectly in the filter, even when installing magento + sample data

Why are numbers (id) displayed? Must be displayed in letters, for example "1ml", "30ml".
Where can I fix it?
![Мезопрепараты-JVue-StorefrontB-Labaratory](https://user-images.githubusercontent.com/20755897/88379599-e3f32880-cdc0-11ea-8e5b-5ffd3a614bf2.jpg)

**Comment by dimasch** [comment]
@ArieRym Why closed?

**Comment by dimasch** [comment]
Ah, ok. Related to #333
