### ISSUE TITLE
Fresh install has Hydration errors

### ISSUE THREAD

**Issue by dixitdeepak** [DivanteLtd/vsf-capybara#462]
## Current behavior

Getting following error while accessing the application

[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
Header tabs are not rendering properly

## Steps to reproduce the issue

Do the fresh installation

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser: Firefox 80.0 (64-bit)
- OS: MacOS Catalina 
- Code Version: master

## Additional information

This similar issue reported in vue-storefront as well  by @SethKitchen  
https://github.com/DivanteLtd/vue-storefront/issues/4773

**Comment by MariaKern** [comment]
The changes of the pull request fixed this issue for me! Thanks! :)
