### ISSUE TITLE
Offline : Product Image is displayed twice on the Product page in offline mode

### ISSUE THREAD

**Issue by ymaheshwari1** [DivanteLtd/vsf-capybara#498]
## Current behavior
The image of the product is duplicated in offline mode. There are two components used in m-product-gallery, SfImage and SfGallery. The SfImage component is rendered in offline mode and SfGallery is rendered in both the online and offline mode

## Expected behavior
Only one of there needs to be rendered in offline mode.

## Steps to reproduce the issue
* Go to Product Page for any product
* Change your network to offline
* See the duplicated image

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
**Screenshot**
![image](https://user-images.githubusercontent.com/41404838/94332015-0424ab00-ffef-11ea-93e7-329613ce76f0.png)

**Comment by ymaheshwari1** [comment]
I want to work on it.

**Comment by Fifciu** [comment]
Sure, go for it @ymaheshwari1
