### ISSUE TITLE
I want to setup continious deployment to test instance So I do not have to waste my time anymore

### ISSUE THREAD

**Issue by rmakara** [DivanteLtd/vsf-capybara#9]
**Context**
In #8 we prepared the test environment. Now we want to setup continuous deployment to that test environment. So we do not have to care about deploying that over and over again.

**Acceptance Criteria**
* After commit automatic pipeline deploys the new changes to test environment.
* I can see the changes in test environment.
* In the comments in pull request I can see checks / link pointing to test environment.

**Comment by qiqqq** [comment]
Fully continuous deployment is not possible at this moment because VS cloud is build to support CD form gitlab and we have a repository on github. The second problem is, there isn't support for git submodules in VS cloud.

Currently, to do deploy, changes must be merged to VS cloud repository.
